### PR TITLE
[MRG] Allow BayesSearchCV to work with sklearn 0.21

### LINKED ISSUE #762: Bug report on BayesSearchCV
Steps to reproduce: 
```
from skopt import BayesSearchCV
from sklearn.datasets import load_digits
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

X, y = load_digits(10, True)
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.75, test_size=.25, random_state=0)

# log-uniform: understand as search over p = exp(x) by varying x
opt = BayesSearchCV(
    SVC(),
    {
        'C': (1e-6, 1e+6, 'log-uniform'),  
        'gamma': (1e-6, 1e+1, 'log-uniform'),
        'degree': (1, 8),  # integer valued parameter
        'kernel': ['linear', 'poly', 'rbf'],  # categorical parameter
    },
    n_iter=32,
    cv=3
)
```
got this error:
```
Traceback (most recent call last):
  File "<stdin>", line 11, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\skopt\searchcv.py", line 288, in __init__
    return_train_score=return_train_score)
TypeError: __init__() got an unexpected keyword argument 'fit_params'
```
Tested on linux and windows. Got same error.

Reason of the bug: `scikit-learn 0.21.0`
How to solve: `pip install scikit-learn==0.20.3`

### PR DESCRIPTION
**Pull request by kitchoi**
Closes #762 

This allows CI to pass on master again and allows other PRs to carry on with the review process (e.g. this one #776).

This is in my opinion a temporary fix to the problem. `sklearn` has deprecated `fit_params` in the class constructor in favor of passing keyword parameters to the fit methods. `scikit-optimize` should probably follow suit.  However that will require a chain of deprecation action.

If the maintainer agrees, I think there should be a separate issue for deprecating `fit_params` in `BayesSearchCV.__init__` and exposing `fit_params` in `BayesSearchCV.fit`.

### CODE REVIEW

**Comment by kitchoi** [comment]
> sklearn has deprecated fit_params in the class constructor in favor of passing keyword parameters to the fit methods. scikit-optimize should probably follow suit. However that will require a chain of deprecation action.
If the maintainer agrees, I think there should be a separate issue for deprecating fit_params in BayesSearchCV.__init__ and exposing fit_params in BayesSearchCV.fit.

Ah I see #772 is already on it :)

**Comment by vakker** [comment]
Is this ready to merge or #772 is the active PR for this issue?

**Comment by betatim** [comment]
Merged on advice of @holgern
