### ISSUE TITLE
BayesSearchCV breaks with scikit-learn 0.19

### ISSUE THREAD

**Issue by amueller** [scikit-optimize/scikit-optimize#466]
BayesSearchCV relies on the privat ``_fit`` which will be removed in 0.19.

We should make it work with 0.18 and 0.19 and ideally use public interfaces only to be future-proof.

**Comment by jnothman** [comment]
See also https://github.com/scikit-learn/scikit-learn/issues/9499

**Comment by baharian** [comment]
I am encountering a relevant error, `AttributeError: 'BayesSearchCV' object has no attribute '_fit'`, when using scikit-optimize to do hyper-parameter optimization. My pipeline used to work before, so my guess is that I had an older version of scikit-learn and/or scikit-optimize (I did an update of some packages yesterday, and, I think, scikit-learn was among them). Is there any clean way to get around this error?

**Comment by jnothman** [comment]
have you checked with scikit-optimize about this? they should not have been
relying on our private methods.

**Comment by betatim** [comment]
I am confused.com. I think the result of this discussion was your [PR](https://github.com/scikit-learn/scikit-learn/pull/9599)

**Comment by jnothman** [comment]
yes, but I still hadn't expected that skopt would maintain something using
private interface in the meantime...

**Comment by betatim** [comment]
I don't think there is another way to do this otherwise? I think right now we copy more code than we should ideally have to to make it work on sklearn 0.18 and 0.19. Is there a way to avoid doing this if we want to support `BayesSearchCV` for versions of sklearn that have already been released?

**Comment by jnothman** [comment]
I think the general rule is that if you use private API, you need to pin your requirements to the versions that satisfy that API. We can't and won't assure consistency across versions in private API. I'm sorry that makes it difficult.

**Comment by betatim** [comment]
> We can't and won't assure consistency across versions in private API. 

That is completely expected. As far as I am concerned this issue was just reporting that this broke/will break in 0.19. Then we changed our code. Clearly the burden of making this work across 0.18, 0.19 and 0.20 etc is up to scikit-opotimize.

It made me think how many past versions of scikit-learn we'd want to support.
