### ISSUE TITLE
ImportError when using skopt with scikit-learn 1.0

### ISSUE THREAD

**Issue by SenneDeproost** [scikit-optimize/scikit-optimize#1076]
When importing Scikit-optimize, the following ImportError is returned:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/skopt/__init__.py", line 55, in <module>
    from .searchcv import BayesSearchCV
  File "/usr/local/lib/python3.7/dist-packages/skopt/searchcv.py", line 16, in <module>
    from sklearn.utils.fixes import MaskedArray
ImportError: cannot import name 'MaskedArray' from 'sklearn.utils.fixes' (/usr/local/lib/python3.7/dist-packages/sklearn/utils/fixes.py)

![image](https://user-images.githubusercontent.com/18738435/136021537-7d270f93-1980-4a6b-b195-ac2c4c67b590.png)

This issue started occurring when upgrading from Scikit-learn 0.24.2 to 1.0.

System dependencies:
Python                      3.7.12
scikit-image              0.18.3
scikit-learn                1.0
scikit-optimize          0.8.1
sklearn                      0.0

**Comment by ConstantinGahr** [comment]
Duplicate of #1059

**Comment by QuentinSoubeyran** [comment]
@SenneDeproost scikit-optimize 0.8.1 is not compatible with scikit-learn 0.24 and higher. A compatible release is in the making. Until then, you should force `scikit-learn<0.24` in `pip` or install from source.

**Comment by kernc** [comment]
Assumed now fixed by v0.9.0 just released.
