### ISSUE TITLE
Can not import "use_named_args"

### ISSUE THREAD

**Issue by mrStasSmirnoff** [scikit-optimize/scikit-optimize#621]
Dear Moderators,

I would like to make use of the "use_named_args" decorator, but cannot import it. since error pops up:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-52-0c6493c7a859> in <module>()
      3 from skopt.plots import plot_convergence
      4 from skopt.plots import plot_objective, plot_evaluations
----> 5 from skopt.utils import use_named_args
      6 #from skopt.plots import plot_histogram, plot_objective_2D

ImportError: cannot import name use_named_args
---------------------------------------------------------------------------
I'm using version 0.4 of the skopt library. Could you please help me with that?
Thanks in advance.

**Comment by chschroeder** [comment]
This is a new decorator that has been introduced in #592 (and merged into master on Jan 6th, 2018) and therefore is not yet included in the 0.4 release.

Possible solutions:
* use v0.5rc1
* install using the master branch
* or wait for 0.5 which should be released soon (see #578).

**Comment by mrStasSmirnoff** [comment]
Oh, great! thank you!
